default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: money
  schema_search_path: public

development:
  <<: *default
test:
  <<: *default
  database: money_test
production:
  <<: *default
